name 'puppet-logrotate'
version '1.1.1'
source 'https://github.com/ehime/puppet-logrotate'
license 'MIT'
summary 'Logrotate module'
description 'Manage logrotate on your servers with Puppet'
project_page 'https://github.com/ehime/puppet-logrotate'
